shervinea/cheatsheet-translation

fr/refresher-linear-algebra.md

I have some translation issue in the file refresher-linear-algebra.md.

 [fr] fixing issues in refresher-linear-algebra

---

CONTRIBUTORS
es/refresher-probability.md

This PR includes translations of about 48% of the content.

[es] Probabilities and Statistics

---

CONTRIBUTORS
zh-tw/cheatsheet-deep-learning.md

This PR contains two parts:
1. Add zh-tw folder and raw markdown.
2. Add deep learning zh-tw translation.

[zh-tw] Deep learning

---

fa/refresher-linear-algebra.md

https://fa.wikipedia.org/wiki/%D9%85%D8%A7%D8%AA%D8%B1%DB%8C%D8%B3_%D9%87%D8%B4%DB%8C%D9%86
برای شنیدن تلفظ درست بر روی بلندگوی
https://translate.google.com/?source=gtx#en/fa/Hessian
کلیک کنید

تلفظ اشتباه

---

CONTRIBUTORS
zh-tw/cheatsheet-supervised-learning.md

Finish the `supervised learning` zh-tw translation. Also add the missing part, please ref to this issue : https://github.com/shervinea/cheatsheet-translation/issues/74

[zh-tw] Supervised learning

---

CONTRIBUTORS
zh-tw/cheatsheet-unsupervised-learning.md
zh-tw/refresher-probability.md

I've finished the unsupervised learning translation work and update `CONTRIBUTOR` accordingly. Thanks!

[zh-tw] Unsupervised learning

---

CONTRIBUTORS
zh-tw/refresher-probability.md

I've finish the Probabilities and Statistics part 👍

[zh-tw] Probabilities and Statistics

---

tr/cheatsheet-unsupervised-learning.md

[tr] Unsupervised Learning

---

tr/cheatsheet-deep-learning.md

deficiencies completed and some minor corrections were made

[tr] Deep learning

---

tr/refresher-probability.md

I have started translate to Turkish. Still in progress.

[tr] Probabilities and Statistics

---

tr/cheatsheet-machine-learning-tips-and-tricks.md

I combined the notes in the translation of @SerayBeser and @ayyucekizrak.
I've done some minor corrections. All of them translated.
However, CS 229 - Machine Learning has been translated into Turkish.

[tr] Machine learning tips and tricks

---

tr/convolutional-neural-networks.md

As well as I've completed the entire translation of this file. 
Please note that the review process can be started. Thank you!

[tr] Convolutional neural networks

---

tr/deep-learning-tips-and-tricks.md

I've completed the entire translation of this title. 
Please note that the review process can be started. Thank you!

[tr] Deep Learning tips and tricks

---

tr/recurrent-neural-networks.md

I translated the CS 230 (Deep Learning) - Recurrent neural networks to Turkish. @shervinea can you please review it?

[tr] Recurrent neural networks

---

CONTRIBUTORS
ko/cheatsheet-machine-learning-tips-and-tricks.md

[ko] Machine learning tips and tricks

---

ja/deep-learning-tips-and-tricks.md

I reviewed #157 before and would like to continue improving the document.

[ja] DL tips and tricks (21-26)

---

tr/cs-221-variables-models.md

Turkish translation has been completed. Ready for the review!

[tr] Variables-based models

---

tr/cs-221-reflex-models.md

It will continue to be translated into Turkish.

[tr] Reflex-based models

---

tr/cs-221-logic-models.md

[tr] Logic-based models

---

tr/cs-221-states-models.md

I translated the CS 221 - State-based models into Turkish. @shervinea can you please review it?
Best regards.

[tr] States-based models

---

ja/cs-229-linear-algebra.md

Some areas don't need to be used Japanese letters.
The other areas need to be used Japanese letters and spaces.

Fixed some Japanese style letters around math area

---

ja/cs-229-unsupervised-learning.md

Some expressions including comma, punctuation and wording are changed.

Some expressions revised in Japanese style

---

ja/cs-229-probability.md

"if and only if" means iff but Japanese sentence is a little bit confusing.

Revised a Japanese sentence in iff.

---

CONTRIBUTORS

The corrected name is: Fares Al-Qunaieer

Name Correction

---

CONTRIBUTORS
pt/cs-229-deep-learning.md

Just a spelling update (fix). Some academic terms used in Portuguese have also been updated.

[pt] Spelling updates (fix)

---

CONTRIBUTORS
README.md
zh-tw/cs-230-convolutional-neural-networks.md

This pull request merges the translation and review submitted in #196, on top of which proper credits have been added.
Many thanks to @kentropy and @kevingo for all their work.

[zh-tw] Convolutional neural networks

---

CONTRIBUTORS
README.md
vi/cs-230-deep-learning-tips-and-tricks.md

Hi,
I have finished my translation to Vietnamese in topic Deep Learning tips. 
Waiting for reviews.

[vi] Deep learning tips and tricks

---

CONTRIBUTORS
README.md
vi/cs-221-logic-models.md

Finished translation Vietnamese in topic Logic models.
Welcome to review.

[vi] Logic models

---

CONTRIBUTORS
README.md
vi/cs-229-probability.md

Hi,
I've finished my translation to Vietnamese with topic Probabilities. Welcome your review.
Thank you.

[vi] Probabilities and Statistics

---

CONTRIBUTORS
README.md
vi/cs-229-linear-algebra.md

Finished my translation to Vietnamese in topic Linear Algebra.
Need to review.

[vi] Linear Algebra

---

CONTRIBUTORS
README.md
et/cs-229-machine-learning-tips-and-tricks.md

So this is my first submission in Estonian. Will try to add Deep Learning and some other ones in the coming days.

[et] Machine Learning tips and tricks
